#!/bin/bash

#  publish_github_pages.sh
#
#  This Xcode Cloud CI script publishes DocC archives generated by the build to
#  a GitHub Pages branch. Each release channel is published into its own
#  subdirectory so integration, staging, and release documentation can coexist.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "${script_dir}/.." && pwd)}"

#  The branch and directory that trigger the GitHub Pages deployment.
GITHUB_PAGES_BRANCH="${GITHUB_PAGES_BRANCH:-feature/docc-hosting}"
GITHUB_PAGES_DIR="${GITHUB_PAGES_DIR:-docs}"

#  GitHub Pages repository settings.
GITHUB_ORGANIZATION="${GITHUB_ORGANIZATION:-Technistic}"
GITHUB_PAGES_REPO="${GITHUB_PAGES_REPO:-ImageDataPicker}"

workspace_doc_archives="${CI_WORKSPACE_PATH}/doc_archives"
pages_root="${repo_root}/${GITHUB_PAGES_DIR}"
pages_doc_root="${pages_root}/documentation"

stash_created="false"
checkout_branch="${CI_BRANCH:-$(git -C "${repo_root}" rev-parse --abbrev-ref HEAD)}"

cleanup() {
    local exit_code=$?

    if git -C "${repo_root}" rev-parse --verify "${checkout_branch}" >/dev/null 2>&1; then
        git -C "${repo_root}" checkout "${checkout_branch}" >/dev/null 2>&1 || true
    fi

    if [[ "${stash_created}" == "true" ]]; then
        git -C "${repo_root}" stash pop >/dev/null 2>&1 || true
    fi

    exit "${exit_code}"
}

trap cleanup EXIT

echo "Publishing DocC documentation for ${CI_PRODUCT:-unknown product}"

rm -rf "${workspace_doc_archives}"
mkdir -p "${workspace_doc_archives}"

mapfile -t docc_archives < <(find "${CI_DERIVED_DATA_PATH}" -type d -name "*.doccarchive" | sort)
if [[ "${#docc_archives[@]}" -eq 0 ]]; then
    echo "No DocC archives found in ${CI_DERIVED_DATA_PATH}."
    exit 0
fi

cp -R "${docc_archives[@]}" "${workspace_doc_archives}/"

git -C "${repo_root}" config user.name "${DOCC_GITHUB_NAME}"
git -C "${repo_root}" config user.email "${DOCC_GITHUB_EMAIL}"

if [[ -n "$(git -C "${repo_root}" status --porcelain)" ]]; then
    git -C "${repo_root}" stash push -u -m "publish-github-pages" >/dev/null 2>&1 || true
    stash_created="true"
fi

git -C "${repo_root}" remote set-url origin "https://${DOCC_GITHUB_USERNAME}:${DOCC_GITHUB_API_TOKEN}@github.com/${GITHUB_ORGANIZATION}/${GITHUB_PAGES_REPO}"
source "${script_dir}/get_version_from_git_ref.sh" >/dev/null

determine_pages_channel() {
    local requested_channel="${DOCC_PAGES_CHANNEL:-${GITHUB_PAGES_CHANNEL:-}}"
    local normalized_release_channel="${release_channel:-}"

    if [[ -n "${requested_channel}" ]]; then
        case "${requested_channel,,}" in
            integration|alpha)
                echo "integration"
                return
                ;;
            staging|beta|rc)
                echo "staging"
                return
                ;;
            release|production|main)
                echo "release"
                return
                ;;
            *)
                echo "${requested_channel,,}"
                return
                ;;
        esac
    fi

    case "${normalized_release_channel,,}" in
        alpha)
            echo "integration"
            ;;
        beta|rc)
            echo "staging"
            ;;
        production|"")
            echo "release"
            ;;
        *)
            echo "${normalized_release_channel,,}"
            ;;
    esac
}

pages_channel="$(determine_pages_channel)"
channel_root="${pages_doc_root}/${pages_channel}"

echo "Publishing documentation channel: ${pages_channel}"

git -C "${repo_root}" fetch origin "${GITHUB_PAGES_BRANCH}"
git -C "${repo_root}" checkout "${GITHUB_PAGES_BRANCH}"

rm -rf "${channel_root}"
mkdir -p "${channel_root}"

for archive in "${workspace_doc_archives}"/*.doccarchive; do
    archive_file="$(basename "${archive}")"
    archive_name="${archive_file%%.doccarchive}"
    archive_slug="$(echo "${archive_name}" | tr '[:upper:]' '[:lower:]')"
    archive_target="${channel_root}/${archive_slug}"

    echo "Processing archive: ${archive}"
    mkdir -p "${archive_target}"
    cp -R "${archive}/"* "${archive_target}/"
done

generate_channel_index() {
    local channel="$1"
    local channel_dir="${pages_doc_root}/${channel}"
    local channel_index="${channel_dir}/index.html"
    local first_archive=""

    if [[ ! -d "${channel_dir}" ]]; then
        return
    fi

    for archive_path in "${channel_dir}"/*; do
        if [[ -d "${archive_path}" ]]; then
            first_archive="$(basename "${archive_path}")"
            break
        fi
    done

    if [[ -z "${first_archive}" ]]; then
        return
    fi

    cat > "${channel_index}" <<EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${CI_PRODUCT:-DocC} ${channel^} Documentation</title>
  <meta http-equiv="refresh" content="0; url=./${first_archive}/">
  <link rel="canonical" href="./${first_archive}/">
</head>
<body>
  <p>Redirecting to <a href="./${first_archive}/">${first_archive}</a>...</p>
</body>
</html>
EOF
}

first_archive_in_channel() {
    local channel="$1"
    local archive_path=""

    if [[ ! -d "${pages_doc_root}/${channel}" ]]; then
        return
    fi

    for archive_path in "${pages_doc_root}/${channel}"/*; do
        if [[ -d "${archive_path}" ]]; then
            basename "${archive_path}"
            return
        fi
    done
}

generate_site_index() {
    local site_index="${pages_root}/index.html"
    local -a discovered_channels=()
    local default_channel=""
    local default_archive=""

    mkdir -p "${pages_doc_root}"

    for candidate in integration staging release; do
        if [[ -d "${pages_doc_root}/${candidate}" ]] && find "${pages_doc_root}/${candidate}" -mindepth 1 -maxdepth 1 -type d | grep -q .; then
            discovered_channels+=("${candidate}")
            if [[ -z "${default_channel}" ]]; then
                default_channel="${candidate}"
                default_archive="$(first_archive_in_channel "${candidate}")"
            fi
        fi
    done

    if [[ -z "${default_channel}" ]]; then
        default_channel="${pages_channel}"
        default_archive="$(first_archive_in_channel "${pages_channel}")"
    fi

    cat > "${site_index}" <<EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${CI_PRODUCT:-DocC} Documentation</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #f4f6fb;
      --panel: #ffffff;
      --text: #172033;
      --muted: #5c6578;
      --border: #d7ddea;
      --accent: #1e5eff;
    }
    body {
      margin: 0;
      min-height: 100vh;
      display: grid;
      place-items: center;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background:
        radial-gradient(circle at top, #dfe9ff 0%, transparent 35%),
        linear-gradient(180deg, #f9fbff 0%, var(--bg) 100%);
      color: var(--text);
    }
    main {
      width: min(720px, calc(100vw - 32px));
      padding: 32px;
      border-radius: 24px;
      background: color-mix(in srgb, var(--panel) 92%, transparent);
      border: 1px solid var(--border);
      box-shadow: 0 20px 60px rgba(23, 32, 51, 0.10);
    }
    h1 {
      margin: 0 0 12px;
      font-size: clamp(2rem, 4vw, 3rem);
      line-height: 1.1;
    }
    p {
      margin: 0 0 24px;
      color: var(--muted);
      font-size: 1rem;
      line-height: 1.6;
    }
    label {
      display: block;
      margin-bottom: 8px;
      font-weight: 600;
    }
    select {
      width: 100%;
      padding: 14px 16px;
      font-size: 1rem;
      border-radius: 14px;
      border: 1px solid var(--border);
      background: #fff;
      color: var(--text);
    }
    .actions {
      display: flex;
      gap: 12px;
      flex-wrap: wrap;
      margin-top: 20px;
    }
    a.button {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      min-width: 180px;
      padding: 12px 16px;
      border-radius: 999px;
      text-decoration: none;
      color: #fff;
      background: var(--accent);
      font-weight: 600;
    }
    .link-list {
      margin-top: 24px;
      padding-top: 20px;
      border-top: 1px solid var(--border);
      display: grid;
      gap: 10px;
    }
    .link-list a {
      color: var(--accent);
      text-decoration: none;
    }
  </style>
</head>
<body>
  <main>
    <h1>${CI_PRODUCT:-DocC} Documentation</h1>
    <p>Select the documentation stream you want to browse. Each channel is published independently so integration, staging, and release docs can stay live at the same time.</p>
    <label for="channel-select">Release channel</label>
    <select id="channel-select"></select>
    <div class="actions">
      <a class="button" id="open-docs" href="./documentation/${default_channel}/${default_archive}/">Open documentation</a>
    </div>
    <div class="link-list" id="direct-links"></div>
  </main>
  <script>
    const channels = [
EOF

    local candidate
    for candidate in "${discovered_channels[@]}"; do
        local archive_name
        archive_name="$(first_archive_in_channel "${candidate}")"
        cat >> "${site_index}" <<EOF
      { name: "${candidate}", title: "${candidate^}", href: "./documentation/${candidate}/${archive_name}/" },
EOF
    done

    cat >> "${site_index}" <<EOF
    ];

    const select = document.getElementById("channel-select");
    const openLink = document.getElementById("open-docs");
    const directLinks = document.getElementById("direct-links");

    channels.forEach((channel) => {
      const option = document.createElement("option");
      option.value = channel.href;
      option.textContent = channel.title;
      select.appendChild(option);

      const link = document.createElement("a");
      link.href = channel.href;
      link.textContent = channel.title + " documentation";
      directLinks.appendChild(link);
    });

    select.value = "${default_channel:+./documentation/${default_channel}/${default_archive}/}";
    select.addEventListener("change", () => {
      openLink.href = select.value;
    });
  </script>
</body>
</html>
EOF
}

generate_channel_index "${pages_channel}"
generate_site_index

git -C "${repo_root}" add "${GITHUB_PAGES_DIR}"

if git -C "${repo_root}" diff --cached --quiet; then
    echo "No DocC changes to publish."
else
    git -C "${repo_root}" commit -m "Updated ${pages_channel} DocC documentation"
    git -C "${repo_root}" push --set-upstream origin "${GITHUB_PAGES_BRANCH}"
fi

echo "Publishing DocC documentation for ${CI_PRODUCT:-unknown product} completed successfully."
