#!/bin/zsh

#  test_xcode_cloud_pr.sh
#  
#
#  Created by Michael Logothetis on 14/7/2025.
#  

echo "GIT BRANCH is $(git branch)"
echo "CI_BRANCH is $CI_BRANCH"
echo "CI_PRIMARY_REPOSITORY_PATH is $CI_PRIMARY_REPOSITORY_PATH"
echo "CI_TAG is $CI_TAG"
echo "CI_PULL_REQUEST_SOURCE_BRANCH is $CI_PULL_REQUEST_SOURCE_BRANCH"
echo "CI_PULL_REQUEST_TARGET_BRANCH is $CI_PULL_REQUEST_TARGET_BRANCH"
echo "CI_PULL_REQUEST_SOURCE_REPO is $CI_PULL_REQUEST_SOURCE_REPO"
echo "CI_PULL_REQUEST_TARGET_REPO is $CI_PULL_REQUEST_TARGET_REPO"
