name: "Test Release"

on:
  # manual trigger but change to any supported event
  # see addl: https://www.andrewhoog.com/post/how-to-build-react-native-android-app-with-github-actions/#3-run-build-workflow
  workflow_dispatch:

jobs:
  build_with_signing:
    runs-on: macos-15
    steps:
      # this was more debug as was curious what came pre-installed
      # GitHub shares this online, e.g. https://github.com/actions/runner-images/blob/macOS-12/20230224.1/images/macos/macos-12-Readme.md
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: create test release content
        run: |
          cd ${{ runner.temp }}
          mkdir -p framework
          mkdir -p framework/ImageDataPicker.xcframework
          touch framework/ImageDataPicker.xcframework/ImageDataPicker.txt
      
      - name: Archive Framework
        run: |
          cd ${{ runner.temp }}/framework
          tar -czf ImageDataPicker.tgz ImageDataPicker.xcframework

      - name: Publish (Draft) Release
        uses: softprops/action-gh-release@v2
        with:
          body: "This is a test release."
          draft: true
          files: ${{ runner.temp }}/framework/ImageDataPicker.tgz
          name: v0.0.1 (Test Release)
          prerelease: true
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          # retention-days: 3

      #- name: Upload application
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: ImageDataPicker.tgz
      #    path: ${{ runner.temp }}/ImageDataPicker.tgz
      #    # you can also archive the entire directory
      #    # path: ${{ runner.temp }}/build
      #    retention-days: 3
